# Generated by Django 4.1.3 on 2022-12-02 21:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Colour(s) associated with the observation.",
                        max_length=200,
                        unique=True,
                        verbose_name="Observation colour(s)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date(s) associated with the observation.",
                        unique=True,
                        verbose_name="Observation date(s)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_name",
                    models.CharField(
                        help_text="Name(s) of the location(s) of observation",
                        max_length=200,
                        unique=True,
                        verbose_name="Observation place name(s)",
                    ),
                ),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Coordinates of the location(s) of observation (latitude, longitude)",
                        srid=4326,
                        unique=True,
                        verbose_name="Observation coordinates",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Time(s) associated with the observation.",
                        unique=True,
                        verbose_name="Observation time(s)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Observation types, e.g., 'lights', 'saucer', 'triangle'.",
                        max_length=200,
                        unique=True,
                        verbose_name="Observation type(s)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date record was created in this database.",
                        verbose_name="Record created",
                    ),
                ),
                (
                    "last_mod",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date record was last modified in this database.",
                        verbose_name="Last modified",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        help_text="Name of the original data source",
                        max_length=200,
                        verbose_name="Source name",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="Web link to the original record (as of time of entry).",
                        verbose_name="Source URL",
                    ),
                ),
                (
                    "obs_txt",
                    models.TextField(
                        help_text="Unmodified text of the original report.",
                        verbose_name="Report text",
                    ),
                ),
                (
                    "obs_colors",
                    models.ManyToManyField(
                        help_text="Colour(s) associated with the observation.",
                        to="ie.color",
                        verbose_name="Observation colour(s)",
                    ),
                ),
                (
                    "obs_dates",
                    models.ManyToManyField(
                        help_text="Date(s) associated with the observation.",
                        to="ie.date",
                        verbose_name="Observation date(s)",
                    ),
                ),
                (
                    "obs_locs",
                    models.ManyToManyField(
                        help_text="Name(s) of the location(s) of observation, i.e., place name, (longitude, latitude)",
                        to="ie.loc",
                        verbose_name="Observation location(s)",
                    ),
                ),
                (
                    "obs_times",
                    models.ManyToManyField(
                        help_text="Time(s) associated with the observation.",
                        to="ie.time",
                        verbose_name="Observation time(s)",
                    ),
                ),
                (
                    "obs_types",
                    models.ManyToManyField(
                        help_text="Observation types, e.g., 'lights', 'saucer', 'triangle'.",
                        to="ie.type",
                        verbose_name="Observation type(s)",
                    ),
                ),
            ],
        ),
    ]
