# Generated by Django 4.1.3 on 2022-12-03 15:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loc",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Coordinates of the location(s) of observation (latitude, longitude)",
                srid=4326,
                verbose_name="Observation coordinates",
            ),
        ),
        migrations.AlterField(
            model_name="loc",
            name="place_name",
            field=models.CharField(
                help_text="Name(s) of the location(s) of observation",
                max_length=200,
                verbose_name="Observation place name(s)",
            ),
        ),
        migrations.AddConstraint(
            model_name="loc",
            constraint=models.UniqueConstraint(
                fields=("place_name", "coordinates"),
                name="Unique for place_name, coordinates pairs",
            ),
        ),
    ]
