# Generated by Django 4.1.4 on 2023-01-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ie", "0004_report_record_junked_alter_loc_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="record_junked",
            field=models.BooleanField(
                default=False,
                help_text="Record marked for deletion",
                verbose_name="Record junked",
            ),
        ),
    ]
